# Generated by Django 6.0.5 on 2026-06-13 10:34

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_contact'),
        ('expenses', '0003_expense_employee_expense_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(default=expenses.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'date')},
            },
        ),
    ]
