# Generated by Django 6.0.5 on 2026-05-18 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter valid Tanzanian number', regex='^(?:\\+255|0)[67][0-9]{8}$')]),
        ),
    ]
