# Generated by Django 6.0.5 on 2026-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
