# Generated by Django 6.0.5 on 2026-05-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
