# Generated by Django 6.0.5 on 2026-05-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tin_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='vrn_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ward',
        ),
    ]
