# Generated by Django 6.0.5 on 2026-05-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quotationitem_cts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='methodology',
        ),
    ]
