# Generated by Django 6.0.5 on 2026-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_remove_quotationitem_methodology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='contact_person',
            new_name='glass_type',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='project_name',
            new_name='profile_type',
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='aluminium_profile',
            field=models.CharField(blank=True, choices=[('6mm', '6mm'), ('5mm', '5mm'), ('8mm', '8mm'), ('10mm', '10mm'), ('12mm', '12mm')], default='Al Pro 100mm', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='glass',
            field=models.CharField(blank=True, choices=[('6mm', '6mm'), ('5mm', '5mm'), ('8mm', '8mm'), ('10mm', '10mm'), ('12mm', '12mm')], default='6mm', max_length=255),
        ),
    ]
