# Generated by Django 6.0.5 on 2026-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_rename_contact_person_quotation_glass_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='aluminium_profile',
            field=models.CharField(blank=True, choices=[('Al Pro 100mm', 'Al Pro 100mm'), ('Al Pro 80mm', 'Al Pro 80mm'), ('IPPP 95mm', 'IPPP 95mm'), ('IPPP 3Truck', 'IPPP 3Truck'), ('IPPP 4Truck', 'IPPP 4Truck')], default='Al Pro 100mm', max_length=255),
        ),
    ]
