# Generated by Django 6.0.5 on 2026-07-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_phone'),
        ('quotations', '0006_alter_quotationitem_aluminium_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customers.customer'),
        ),
    ]
