# Generated by Django 6.0.5 on 2026-07-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_alter_quotation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='aluminium_profile',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Al Pro 100mm', 'Al Pro 100mm'), ('U Channel', 'U Channel'), ('Al Pro 80mm', 'Al Pro 80mm'), ('EPPP 95mm', 'EPPP 95mm'), ('EPPP 95mm White', 'EPPP 95mm White'), ('EPPP 95mm Black', 'EPPP 95mm Black'), ('EPPP 95mm Grey', 'EPPP 95mm Grey'), ('EPPP 3Truck White', 'EPPP 3Truck 150mm White'), ('EPPP 3Truck Black', 'EPPP 3Truck 150mm Black'), ('EPPP 3Truck Grey', 'EPPP 3Truck 150mm Grey'), ('EPPP 4Truck White', 'EPPP 4Truck White'), ('EPPP 4Truck Black', 'EPPP 4Truck Black'), ('EPPP 4Truck Grey', 'EPPP 4Truck Grey')], default='Al Pro 100mm', max_length=255),
        ),
    ]
