# Generated by Django 6.0.5 on 2026-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_alter_quotationitem_aluminium_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling (TZS)'), ('USD', 'US Dollar (USD)')], default='TZS', max_length=5),
        ),
    ]
