# Generated by Django 6.0.5 on 2026-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_alter_quotationitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='aluminium_profile',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Al Pro 100mm', 'Al Pro 100mm'), ('Metal Al Pro 100mm Grey', 'Metal Al Pro 100mm Grey'), ('U Channel', 'U Channel'), ('Al Pro 80mm Black', 'Al Pro 80mm Black'), ('EPPP 95mm', 'EPPP 95mm'), ('EPPP 95mm White', 'EPPP 95mm White'), ('EPPP 95mm Black', 'EPPP 95mm Black'), ('EPPP 95mm Grey', 'EPPP 95mm Grey'), ('EPPP 3Truck White', 'EPPP 3Truck 150mm White'), ('EPPP 3Truck Black', 'EPPP 3Truck 150mm Black'), ('EPPP 3Truck Grey', 'EPPP 3Truck 150mm Grey'), ('EPPP 4Truck White', 'EPPP 4Truck White'), ('EPPP 4Truck Black', 'EPPP 4Truck Black'), ('EPPP 4Truck Grey', 'EPPP 4Truck Grey')], default='Metal Al Pro 100mm Grey', max_length=255),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='glass',
            field=models.CharField(blank=True, choices=[('6mm Tinted grey', '6mm Tinted grey'), ('6mm Light Grey', '6mm Light Grey'), ('Frosted 6mm', 'Frosted 6mm'), ('5mm clear,5m one way grey', '5mm clear,5m one way grey'), ('8mm', '8mm'), ('10mm', '10mm'), ('12mm', '12mm')], default='6mm Light Grey', max_length=255),
        ),
    ]
